services:
  mysql-auth:
    ports: !reset []
    volumes:
      - mysql-auth-test-data:/var/lib/mysql
      - ./docker/mysql/auth-test:/docker-entrypoint-initdb.d

  mysql-orders:
    volumes:
      - mysql-orders-test-data:/var/lib/mysql
      - ./docker/mysql/orders-test:/docker-entrypoint-initdb.d

  mysql-products:
    ports: !reset []
    volumes:
      - mysql-products-test-data:/var/lib/mysql
      - ./docker/mysql/products-test:/docker-entrypoint-initdb.d

  rabbitmq:
    ports: !reset []
    volumes:
      - rabbitmq_testing_data:/var/lib/rabbitmq
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

  redis:
    ports: !reset []

  auth-php:
    environment:
      APP_ENV: testing
      DB_DATABASE: auth_test
    ports: !reset []

  auth-nginx:
    ports: !reset []

  order-php:
    environment:
      APP_ENV: testing
      DB_DATABASE: orders_test
    ports: !reset []

  order-worker:
    environment:
      APP_ENV: testing
      DB_DATABASE: orders_test
    ports: !reset []

  order-outbox-worker:
    environment:
      APP_ENV: testing
      DB_DATABASE: orders_test
    ports: !reset []

  order-nginx:
    ports: !reset []

  product-php:
    environment:
      APP_ENV: testing
      DB_DATABASE: products_test
    ports: !reset []

  product-worker:
    environment:
      APP_ENV: testing
      DB_DATABASE: products_test
    ports: !reset []

  product-outbox-worker:
    environment:
      APP_ENV: testing
      DB_DATABASE: products_test
    ports: !reset []

  product-nginx:
    ports: !reset []

  api-php:
    environment:
      APP_ENV: testing
    ports: !reset []

  api-nginx:
    ports: !reset []

  frontend:
    ports: !reset []

volumes:
  mysql-auth-test-data:
  mysql-orders-test-data:
  mysql-products-test-data:
  rabbitmq_testing_data:
